### ISSUE TITLE
Minecraft Time Cycle

### ISSUE THREAD

**Issue by stormlabsDE** [flytegg/mcu-website#101]
I think either something like that image 
https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/bc/Day_Night_Clock_24h.png/revision/latest?cb=20130103232456
or a convert function would be great to have in the mcutils collection

**Comment by joshbker** [comment]
Hi, I think the image you linked is wrong, or maybe it just doesn't load for me. But a time util would be a great idea, thanks :)

**Comment by stephendotgg** [comment]
Ok

**Comment by stephendotgg** [comment]
@stormlabsDE 
Done
With convert function
Thanks for idea.
[https://mcutils.com/daylight-cycle](https://mcutils.com/daylight-cycle)
