### ISSUE TITLE
Small text generator

### ISSUE THREAD

**Issue by xdDirti** [flytegg/mcu-website#105]
Sort of like this, but integrated into the website:
[https://smalltext.io/](url)

A lot of modern servers use this, and it would be awesome to see it implemented here.

**Comment by itsstephenagain** [comment]
I agree 100% this will be such a useful util

**Comment by itsstephenagain** [comment]
Done
I am speed!
Thanks for the suggestion
[https://mcutils.com/small-text-converter](https://mcutils.com/small-text-converter)
