### ISSUE TITLE
Minecraft Item ID List

### ISSUE THREAD

**Issue by xdDirti** [flytegg/mcu-website#112]
I know this will be a pain to make... however I cannot exaggerate the amount of times ive went through a website like this when I was newer to making MC servers
https://minecraftitemids.com/

**Comment by stephendotgg** [comment]
Ok i agree will make.

**Comment by stephendotgg** [comment]
@xdDirti do you mean like this? For sub 1.13 stuffs?
https://minecraft-ids.grahamedgecombe.com/

**Comment by stephendotgg** [comment]
All sorted for ya mate 👍 Thanks for the idea.
http://mcutils.com/item-ids
