### ISSUE TITLE
Minecraft sounds + particles list

### ISSUE THREAD

**Issue by marcelpkg** [flytegg/mcu-website#113]
This one could be really aids to code, may not be as useful so isnt really one of those big ones

For sounds if you really wanted to go deadly and go the extra step of drinking more energy drinks you could add a play button to preview the sound (extra deadly impossible mode)

**Comment by stephendotgg** [comment]
Thank you for the issue! Even though you made this issue first, I will close it as there is a duplicate which has more information.
