### ISSUE TITLE
Polish letters in small text converter.

### ISSUE THREAD

**Issue by XHealthy** [flytegg/mcu-website#116]
Is it possible to add Polish letters to SMALL TEXT CONVERTER? "ąćłśóżź".

![image](https://github.com/flytegg/mcu-website/assets/99989097/214864af-373c-49e6-a22b-573395e5df18)

**Comment by xdDirti** [comment]
I am pretty sure that the font does not support polish letters, as well as capital letters

**Comment by stephendotgg** [comment]
Well believe it or not, it does appear to
ąćłśóżź -> ᴀ̨ᴄ́ᴌśᴏ́ᴢ̇ᴢ́

Based on this, I will look @ adding other languages yes

**Comment by XHealthy** [comment]
So. Any progress?

**Comment by DanIsLit** [comment]
@XHealthy Should be live now. Let me know if you have any problems.
