### ISSUE TITLE
Description error on small font on homepage

### ISSUE THREAD

**Issue by xdDirti** [flytegg/mcu-website#117]
![image](https://github.com/flytegg/mcu-website/assets/64794665/528855a9-6b59-4aa7-b3c1-ee47357d9a3f)

**Comment by stephendotgg** [comment]
Really? I swear I fixed this

**Comment by Nuckerr** [comment]
This is a good bug lol

**Comment by stephendotgg** [comment]
Yes, I did fix this, by adding @html to the shortDescription in the sidebar & homepage
![image](https://github.com/flytegg/mcu-website/assets/138625055/0037603f-da60-4707-8222-392cf8fdf9e3)
Works fine for me?

**Comment by stephendotgg** [comment]
Maybe this is a browser issue or smth so I will just use actual copy/paste small text instead.
