### ISSUE TITLE
Server info page. (Add ip and get statistics about the server.)

### ISSUE THREAD

**Issue by Pan-nav** [flytegg/mcu-website#12]

**Comment by sttephen** [comment]
Love that idea

**Comment by Difluoride** [comment]
https://github.com/spravil/PHP-Minecraft-Server-Status-Query/tree/master - May be a decent starting point, doesn't require plugins or Query Mode - may need updating as it's seems old

**Comment by Dawsson** [comment]
for inspiration for anyone who hasn't used a tool like this before: https://mcsrvstat.us/

**Comment by sttephen** [comment]
Done
