### ISSUE TITLE
[ Color Text Generator ] Remove Testing 123

### ISSUE THREAD

**Issue by MLGPenguin** [flytegg/mcu-website#121]
I get the feeling this shouldn't be here 👀 
<img width="293" alt="image" src="https://github.com/flytegg/mcu-website/assets/72254337/c5ed2b74-d2c5-4864-abfe-ec571b2cb855">
Possibly related to #50

**Comment by Difluoride** [comment]
@stephendotgg you do the crime, you do the time. Git Blame says it's you, relating to #119 Commit cadbb0ff51a38cebeff31864c2b8ead6a5a55f5f

**Comment by MLGPenguin** [comment]
_lol_, You have some speedy response times with those tags Reece

Also upon further consideration, this is not related to issue-50

**Comment by stephendotgg** [comment]
![image](https://github.com/flytegg/mcu-website/assets/138625055/1fd3a1ef-cf90-49a0-8551-a934e093de86)
