### ISSUE TITLE
Skin stealer not rendering any skin properly

### ISSUE THREAD

**Issue by xSenny** [flytegg/mcu-website#122]
I just added my mc name to Skin Stealer page, and I cant find the skin, it s just the "hologram" of my name.
![Screenshot_1](https://github.com/flytegg/mcu-website/assets/95770932/6da7c978-18a2-4eb8-b27f-d5b596a424ad)

**Comment by akkkih** [comment]
**Note:** no skins work, the whole util has broken

**Comment by joshbker** [comment]
Hi this is due to our dependency on Crafatar, the popular skin API.

Crafatar is currently down - I can't see anywhere about planned downtime 😥

**Comment by stephendotgg** [comment]
API back up
![image](https://github.com/flytegg/mcu-website/assets/138625055/62322839-ff98-4f32-8930-dfffae18d16f)
