### ISSUE TITLE
Please add It's Beginning to Look a Lot Like Christmas on the list of NBS songs.

### ISSUE THREAD

**Issue by YopalCodes** [flytegg/mcu-website#136]
Here's the NBS file I imported from a MIDI file using NoteBlockStudio

https://www.mediafire.com/file/ocnm5c0pqxyn0ii/ItsBeginningToALotLikeChristmas.nbs/file

**Comment by stephendotgg** [comment]
Sure, done

For future reference, the site just uses https://github.com/flytegg/nbs-songs under the hood. Feel free to just PR any new songs you find and it'll deploy automatically once merged.
