### ISSUE TITLE
Inventory Slots issue

### ISSUE THREAD

**Issue by xSenny** [flytegg/mcu-website#138]
The Inventory Slots are not really true, at least the Player section, when I use PlayerInventory#setItem(40, item);, the item is set on the second hand slot.

**Comment by Pan-nav** [comment]
I'll fix this up asap, if someone could assign me I'll appreciate it. Most of the slots are outdated, so I'll test and change them all.

**Comment by Pan-nav** [comment]
> The Inventory Slots are not really true, at least the Player section, when I use PlayerInventory#setItem(40, item);, the item is set on the second hand slot.

All the inventory slots are outdated. They are pre 1.12, I have finished creating the new slot screenshots and I will soon fix it in the code aswell ;)
