### ISSUE TITLE
Add PufferfishMC to server jars

### ISSUE THREAD

**Issue by TheRedMagic** [flytegg/mcu-website#160]
Add PufferfishMC to server jars
https://pufferfish.host/downloads

**Comment by Dawsson** [comment]
![image](https://github.com/flytegg/mcu-website/assets/88049488/d9c4e1a0-ae47-43e6-9f16-89ca7d2415a5)

heres protocol libs stats. Wonder if its useless as we have purpur already?

**Comment by Dawsson** [comment]
Its next up in line for bukkit based servers though, plus a good api iirc

**Comment by TheRedMagic** [comment]
Pufferfish is still a really good papermc fork

**Comment by stephendotgg** [comment]
Ok sure

**Comment by stephendotgg** [comment]
Done thanks for the suggestion partner
