### ISSUE TITLE
Purpur 1.20.2 not updateed

### ISSUE THREAD

**Issue by Dawsson** [flytegg/mcu-website#161]
Purpur 1.20.2 has been added at 6:33 PM today, it is currently 6:35. Please update I cannot live without it. ( Can we find a way to automatically update instead of placing json data? )

**Comment by Dawsson** [comment]
Possibly could wait until I make the plugin portal server wrapper? Not sure if I will make it or not though

**Comment by stephendotgg** [comment]
This was updated a while ago forgot to close the issue sorry.
