### ISSUE TITLE
[Util Change]: Add latest version download link to Server Jars downloader

### ISSUE THREAD

**Issue by realdeadbeef** [flytegg/mcu-website#166]
### Util Name

server-jars

### Changes

If you could add a "Download latest version button" for each type (velocity, paper, etc..) then people could use this in scripts to automatically download the latest version of the jar.

### Extra Info

PaperMC currently doesn't offer a "latest release" download link since they changed from their V1 to V2 API.

**Comment by joshbker** [comment]
Thanks for the suggestion, this has been implemented with #167. Which features a "latest" value as the version, e.g. https://mcutils.com/api/server-jars/paper/latest (you could also add a /download to the end to get a direct download link)
