### ISSUE TITLE
[Util Suggestion]: add numbers with that font on mcutils, example:

### ISSUE THREAD

**Issue by Code-Dev23** [flytegg/mcu-website#177]
### Description

![image](https://github.com/flytegg/mcu-website/assets/126022433/72b53038-10b1-44f0-a372-07f1d125cc2a)

**Comment by StillLutto** [comment]
I agree.

**Comment by joshbker** [comment]
These look to be done via a custom resource pack - I'm not aware of any number unicodes which match the small text unicode. If you have the unicodes, feel free to send them and we can implement it.

**Comment by Code-Dev23** [comment]
https://lingojam.com/TinyTextGenerator

**Comment by stephendotgg** [comment]
> https://lingojam.com/TinyTextGenerator

As stated, these do not render in-game. See:

![image](https://github.com/flytegg/mc-utils/assets/138625055/b03a6b5a-7f23-4642-8568-258236a17f37)

![image](https://github.com/flytegg/mc-utils/assets/138625055/0542cea6-4c2c-4958-817b-7ab967d750c2)

**Comment by Code-Dev23** [comment]
![image](https://github.com/user-attachments/assets/14f971f7-f0c3-429f-9e57-24f545a27db1)
because you have to use superscript

**Comment by Code-Dev23** [comment]
![image](https://github.com/user-attachments/assets/bb879ddd-4d05-42a2-923f-ddc46a7ca72f)

**Comment by stephendotgg** [comment]
@Code-Dev23 - No, we have been down this avenue. As you can see, it looks terrible and I've not seen this used on any self respecting server. It is not a good enough match to the letters.

![image](https://github.com/user-attachments/assets/a7866786-47a8-493b-841c-8f8d738ccb9e)
