### ISSUE TITLE
[Server Jars] Add remaining server software support

### ISSUE THREAD

**Issue by sttephen** [flytegg/mcu-website#38]

**Comment by Dawsson** [comment]
support for paper, but what about support for purpur/pufferfish?

**Comment by Nuckerr** [comment]
This shouldn't be hard to implement, just interface with this api: https://docs.papermc.io/misc/downloads-api

**Comment by stephendotgg** [comment]
Thanks!

**Comment by stephendotgg** [comment]
Added purpur & paper. Thanks @Nuckerr for the API link and @Dawsson for speeding up the process 💪
