### ISSUE TITLE
MOTD issue

### ISSUE THREAD

**Issue by Dawsson** [flytegg/mcu-website#95]
https://mcutils.com/server-info#ip=104.223.107.176:25581

![image](https://github.com/flytegg/mcu-website/assets/88049488/20437750-d35b-447a-8048-fecb53441e16)

![image](https://github.com/flytegg/mcu-website/assets/88049488/7a645765-7f4b-4496-b0a7-2e1c7e8adf36)

**Comment by itsstephenagain** [comment]
thx

**Comment by DanIsLit** [comment]
Server closed, can't reproduce.
