### ISSUE TITLE
"Apply skin" URL parameter is undefined

### ISSUE THREAD

**Issue by JovannMC** [flytegg/mcu-website#99]
When using the skin stealer util, the URL parameter when you press "Apply Skin" is always undefined
Tested on mobile and PC

![skinstealer 1](https://github.com/flytegg/mcu-website/assets/45893380/8a92ed40-a33f-4191-81ac-ee14718cacb5)
![skinstealer 2](https://github.com/flytegg/mcu-website/assets/45893380/1f8fbf78-7911-47d9-b240-a5bc7da61dab)

**Comment by joshbker** [comment]
Hi this is due to the fact that Mojang/Microsoft have broken this API integration for applying skins directly, we won't change this until this is fixed by them as no matter the value we provide it doesn't work. Thanks for your efforts so far in bug hunting though we really appreciate it <3
